# Generated by Django 5.1.7 on 2025-03-30 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitemApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('tempo_preparo', models.TimeField()),
                ('dificuldade', models.CharField(max_length=25)),
                ('quantidade_visualizacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaComprasIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=25)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to='KitemApp.ingrediente')),
                ('id_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='KitemApp.listacompras')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=25)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='KitemApp.ingrediente')),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='KitemApp.receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='KitemApp.usuario'),
        ),
        migrations.AddField(
            model_name='listacompras',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to='KitemApp.usuario'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='KitemApp.receita')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='KitemApp.usuario')),
            ],
        ),
    ]
