# Generated by Django 5.2 on 2025-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(help_text="Nome do ingrediente", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "db_table": "tab_ingrediente",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
