# Generated by Django 5.1.7 on 2025-04-18 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaComprasIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=25)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to='core.ingrediente')),
                ('id_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.listacompras')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('tempo_preparo', models.TimeField()),
                ('dificuldade', models.CharField(max_length=25)),
                ('quantidade_visualizacao', models.IntegerField(default=0)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('unidade_medida', models.CharField(max_length=25)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core.ingrediente')),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receita')),
            ],
        ),
    ]
