# Generated by Django 5.1.7 on 2025-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listacompras_listacomprasingrediente_receita_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="imagem",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="receita",
            name="restricao_alimentar",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="receita",
            name="tipo",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="receita",
            name="descricao",
            field=models.CharField(max_length=1500),
        ),
    ]
