# Generated by Django 5.1.7 on 2025-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_receita_imagem_receita_restricao_alimentar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="imagem",
            field=models.URLField(max_length=600, null=True),
        ),
    ]
